export type ListCita = {
    appointmentId : number,
    programId : number,
    programName : string,
    appointmentStatus : string,
    groupBased : boolean,
    creationDate : string,
    personId : number,
    name : string,
    lastName : string,
    secondLastName : string,
    isInPerson : boolean,
    startTime : Date,
    endTime : Date,
    reason : string,
    tutorId : number,
    meetingRoom : string,
    tutorName : string,
    tutorLastName : string,
    tutorSecondLastName : string,
    tutorEmail : string,
    commentId : number,
    message : string
}